---
- name: "Getting username"
  command: whoami
  changed_when: False
  register: logged_user

- name: "Including general vars to OS distibution ({{ansible_distribution}})"
  include_vars: "{{ ansible_distribution }}.yml"
